### ISSUE TITLE
Blender 3.0 errors

### ISSUE THREAD

**Issue by ShnitzelKiller** [absolute-quantum/cats-blender-plugin#323]
In case this helps with getting the plugin compatible with the latest version of Blender, I have found a few errors that pop up in this version on an avatar that behaved fine in 2.92. 

- When I try to bake my model, I get the following errors:

```
START BAKE
Un-mirroring source CATS UV data
Un-mirroring source CATS UV data
Un-mirroring source CATS UV data
Un-mirroring source CATS UV data
Un-mirroring source CATS UV data
Baking diffuse for objects: Body.001,cf_m_shoes_cheersboots (Instance) (Instance).001,shirtpants.001,skirt.001,underclothes.001
Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 384, in execute
    self.perform_bake(context)
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 622, in perform_bake
    self.bake_pass(context, "diffuse", "DIFFUSE", {"COLOR"}, [obj for obj in collection.all_objects if obj.type == "MESH"],
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 294, in bake_pass
    context.scene.render.bake.use_pass_ambient_occlusion = "AO" in bake_pass_filter
AttributeError: 'BakeSettings' object has no attribute 'use_pass_ambient_occlusion'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 384, in execute
    self.perform_bake(context)
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 622, in perform_bake
    self.bake_pass(context, "diffuse", "DIFFUSE", {"COLOR"}, [obj for obj in collection.all_objects if obj.type == "MESH"],
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 294, in bake_pass
    context.scene.render.bake.use_pass_ambient_occlusion = "AO" in bake_pass_filter
AttributeError: 'BakeSettings' object has no attribute 'use_pass_ambient_occlusion'

location: <unknown location>:-1
```

- when I try to "Fix Model" an imported MMD model, I get this:
```
Fixing Model:

Collections:
 Collection collection
DOUBLE ENTRIES:
RENAME:
\Left arm | Bip_UpperArm_\L
\Left ankle | \LFoot
REWEIGHT:
\Left elbow | ElbowAux_\L
\Left leg | LegD_001_\L
DOUBLES END
Info: Applied modifier was not first, result may not be as expected
Collections:
 Collection collection
Collections:
 Collection collection
CHECK TRANSFORMS: 1.0 1.0 1.0
COMBINE MATERIALS!
Collections:
 Collection collection
Light None
Camera None
Model_arm POSE
Model_mesh None
Info: Combined 11 materials!
Collections:
 Collection collection
Warning: No mesh data to join
GOOGLE DICT UPDATE!


DEBUG: Translating 操作
YOU GOT BANNED BY GOOGLE!
Collections:
 Collection collection
MASS MERGING
['UpperBody', 'UpperBody2', 'Spine01', 'Spine02', 'Spine03']
UpperBody2
Spine01
Spine02
FIX TWIST BONES
[]
1. no HandTwist_L
1. no HandTwist_R
1. no ArmTwist_L
1. no ArmTwist_R
[]
BUG: Neck tried to mix weights with itself!
BUG: Head tried to mix weights with itself!
Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 1097, in execute
    if vg.name not in bones_to_delete:
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 1097, in execute
    if vg.name not in bones_to_delete:
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

location: <unknown location>:-1
```

Just to be clear, the exact same operations work on these model when opened in Blender 2.92.

**Comment by feilen** [comment]
Try the latest development, I just fixed that like yesterday-ish

**Comment by ShnitzelKiller** [comment]
I tried out the development branch. "Fix model" still crashes with that error. Baking doesn't crash, but the result looks like this: 
![Screenshot 2021-12-06 143728](https://user-images.githubusercontent.com/6132502/144934131-a700c184-fa9c-4ebc-af69-6cc6d64c2055.png)

The console output is
```

**Comment by feilen** [comment]
From your picture, it looks like it may have the scale all wrong. Could you try applying the scale for the original model and re-baking? 

If that doesn't work, feel free to send me your .blend (with textures packed) and I'll try to take a look ASAP.

**Comment by HazieX** [comment]
> Try the latest development, I just fixed that like yesterday-ish

It doesnt work, ive tried for the whole day and tried different versions. I'm trying to create eyetracking but instead it fucks up my eye shapekeys and says the python error:

Error: Python: Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 384, in execute
    self.perform_bake(context)

**Comment by HazieX** [comment]
> Try the latest development, I just fixed that like yesterday-ish

I dont get the error anymore but it still ruins the shapekeys and eye tracking doesnt want to work. Please fix.

**Comment by mac4kent** [comment]
I did get download and add-ons then enable and click Developers then restart Blender 3.0 then open cause wait not work see picture. Only for Mac. Do not use Windows.
<img width="450" alt="Screen Shot 2022-01-06 at 3 01 05 AM" src="https://user-images.githubusercontent.com/4253305/148373049-19e4bfee-86f2-4992-854b-6f3a5af7e6d5.png">
<img width="698" alt="Screen Shot 2022-01-06 at 3 02 18 AM" src="https://user-images.githubusercontent.com/4253305/148373130-af06bf07-6ec8-47e9-a919-51e41590be1c.png">
